# ---------------------------------------------------------------------------
#
# Configuration options for Wukong
#   http://github.com/infochimps/wukong
#
# !! Don't edit this file !!
# Instead, create a new file wukong-site.yaml and set your options there
#

#
# In the wukong-site.yaml file, set the :hadoop_home to your hadoop installation
# directory -- i.e. if your hadoop runner is
#
#   /usr/local/share/hadoop/bin/hadoop
#
# then your hadoop_home is /usr/local/share/hadoop
#

# :hadoop_home:                     /usr/local/share/hadoop

# ---------------------------------------------------------------------------
#
# Script options
#

# Run as local or as hadoop?
:default_run_mode:                  hadoop

# The command to run when a nil mapper or reducer is given.
:default_mapper:                    /bin/cat
:default_reducer:                   /bin/cat

# Script defaults
:runner_defaults:
    # field separator for sorting 
    # :key_field_separator:           "'\\t'"
    # field separator for partitioning (distributing among reducers)
    # :output_field_separator:        "'\\t'"
    
